/********* add the action types below ************ */

export const CUSTOMER_SIGN_UP = "CUSTOMER_SIGN_UP";
export const CUSTOMER_SIGN_UP_SUCCESSFUL = "CUSTOMER_SIGN_UP_SUCCESSFUL";
export const CUSTOMER_SIGN_UP_FAILED = "CUSTOMER_SIGN_UP_FAILED";

export const CUSTOMER_LOGIN_INIT = "CUSTOMER_LOGIN_INIT";
export const CUSTOMER_LOGIN_PHONENUMBER = "CUSTOMER_LOGIN_PHONENUMBER";
export const CUSTOMER_LOGIN_SUCCESSFUL = "CUSTOMER_LOGIN_SUCCESSFUL";
export const CUSTOMER_LOGIN_FAILED = "CUSTOMER_LOGIN_FAILED";

export const CUSTOMER_OTP_VERIFICATION_INIT = "CUSTOMER_OTP_VERIFICATION_INIT";
export const CUSTOMER_OTP_VERIFICATION_SUCCESS =
  "CUSTOMER_OTP_VERIFICATION_SUCCESS";
export const CUSTOMER_OTP_VERIFICATION_FAILED =
  "CUSTOMER_OTP_VERIFICATION_FAILED";

export const FOODSTALLS_DETAILS_LOADED = "FOODSTALLS_DETAILS_LOADED";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const RESET_CART = "RESET_CART";
export const GET_ACTIVE_FC = "GET_ACTIVE_FC";
export const SET_ACTIVE_FS = "SET_ACTIVE_FS";
export const RESET_CUSTOMER_STORE = "RESET_CUSTOMER_STORE";

export const SET_ACTIVE_MENU_ITEM = "SET_ACTIVE_MENU_ITEM";
export const GET_ACTIVE_MENU_ITEM = "GET_ACTIVE_MENU_ITEM";
