/********* add the action types below ************ */

export const SIGN_UP_INIT = "SIGN_UP_INIT"
export const OTP_VERIFICATION = "otpVerification";
export const SIGN_UP_SUCCESSFUL = "signupSuccessful";
export const SIGN_UP_FAILED = "signupFailed";


export const MERCHANT_SIGN_UP_OTP_VERIFY_INIT = "MERCHANT_SIGN_UP_OTP_VERIFY_INIT";
export const MERCHANT_SIGNUP_OTP_VERIFY_SUCCESS = "MERCHANT_SIGNUP_OTP_VERIFY_SUCCESS";
export const MERCHANT_SIGNUP_OTP_FAILED = "MERCHANT_SIGNUP_OTP_FAILED";
export const MERCHANT_FORGET_PASSWORD_INIT = "MERCHANT_FORGET_PASSWORD_INIT";
export const MERCHANT_FORGET_PASSWORD_SUCCESS = "MERCHANT_FORGET_PASSWORD_SUCCESS";
export const MERCHANT_FORGET_PASSWORD_FAILED = "MERCHANT_FORGET_PASSWORD_FAILED";

export const MERCHANT_LOGIN_INIT = "MERCHANT_LOGIN_INIT";
export const MERCHANT_LOGIN_SUCCESS = "MERCHANT_LOGIN_SUCCESS";
export const MERCHAT_LOGIN_FAILED = "MERCHAT_LOGIN_FAILED";
export const MERCHANT_LOGOUT = "MERCHANT_LOGOUT";


export const MERCHANT_FORGET_PWD_OTP_INIT = "MERCHANT_FORGET_PWD_OTP_INIT";
export const MERCHANT_FORGET_PWD_OTP_SUCCESS = "MERCHANT_FORGET_PWD_OTP_SUCCESS";
export const MERCHANT_FORGET_PWD_OTP_FAIL = "MERCHANT_FORGET_PWD_OTP_FAIL";

export const MERCHANT_CREATE_NEW_PWD_INIT = "MERCHANT_CREATE_NEW_PWD_INIT";
export const MERCHANT_CREATE_NEW_PWD_SUCCESS = "MERCHANT_CREATE_NEW_PWD_SUCCESS";
export const MERCHANT_CREATE_NEW_PWD_FAILED = "MERCHANT_CREATE_NEW_PWD_FAILED";


