/********* add the action types below ************ */

export const GET_MERCHANT_DETAILS_INIT = "GET_MERCHANT_DETAILS_INIT";
export const GET_MERCHANT_DETAILS_SUCCESS = "GET_MERCHANT_DETAILS_SUCCESS";
export const GET_MERCHAT_DETAILS_FAILED = "GET_MERCHAT_DETAILS_FAILED";
export const CLEAR_MERCHANT_DETAILS_ON_LOGOUT = "CLEAR_MERCHANT_DETAILS_ON_LOGOUT";

export const GET_SELECTED_FOOD_STALL_FROM_DROPDOWN = "GET_SELECTED_FOOD_STALL_FROM_DROPDOWN";
export const ADD_FOODSTALL_TO_MERCHANT_FROM_HEADER = "ADD_FOODSTALL_TO_MERCHANT_FROM_HEADER";
export const UPDATE_MERCHANT_DETAILS_INIT = "UPDATE_MERCHANT_DETAILS_INIT";
export const UPDATE_MERCHANT_DETAILS_SUCCESS = "UPDATE_MERCHANT_DETAILS_SUCCESS";
export const UPDATE_MERCHANT_DETAILS_FAILED = "UPDATE_MERCHANT_DETAILS_FAILED";

export const GET_PROFILE_PICTURE = "GET_PROFILE_PICTURE";
export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";
export const ADD_CATEGORY_INIT = "ADD_CATEGORY_INIT";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";
export const FETCH_CATEGORY_INIT = "FETCH_CATEGORY_INIT";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILED = "FETCH_CATEGORY_FAILED";
export const UPDATE_CATEGORY_INIT = "UPDATE_CATEGORY_INIT";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";

export const ADD_SUB_CATEGORY_INIT = "ADD_SUB_CATEGORY_INIT";
export const ADD_SUB_CATEGORY_SUCCESS = "ADD_SUB_CATEGORY_SUCCESS";
export const ADD_SUB_CATEGORY_FAILED = "ADD_SUB_CATEGORY_FAILED";
export const FETCH_SUB_CATEGORY_INIT = "FETCH_SUB_CATEGORY_INIT";
export const FETCH_SUB_CATEGORY_SUCCESS = "FETCH_SUB_CATEGORY_SUCCESS";
export const FETCH_SUB_CATEGORY_FAILED = "FETCH_SUB_CATEGORY_FAILED";
export const UPDATE_SUB_CATEGORY_INIT = "UPDATE_SUB_CATEGORY_INIT";
export const UPDATE_SUB_CATEGORY_SUCCESS = "UPDATE_SUB_CATEGORY_SUCCESS";
export const UPDATE_SUB_CATEGORY_FAILED = "UPDATE_SUB_CATEGORY_FAILED";
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS";
export const DELETE_SUB_CATEGORY_FAILED = "DELETE_SUB_CATEGORY_FAILED";

export const ADD_CUISINE_INIT = "ADD_CUISINE_INIT";
export const ADD_CUISINE_SUCCESS = "ADD_CUISINE_SUCCESS";
export const ADD_CUISINE_FAILED = "ADD_CUISINE_FAILED";
export const FETCH_CUISINE_INIT = "FETCH_CUISINE_INIT";
export const FETCH_CUISINE_SUCCESS = "FETCH_CUISINE_SUCCESS";
export const FETCH_CUISINE_FAILED = "FETCH_CUISINE_FAILED";
export const UPDATE_CUISINE_INIT = "UPDATE_CUISINE_INIT";
export const UPDATE_CUISINE_SUCCESS = "UPDATE_CUISINE_SUCCESS";
export const UPDATE_CUISINE_FAILED = "UPDATE_CUISINE_FAILED";
export const DELETE_CUISINE_SUCCESS = "DELETE_CUISINE_SUCCESS";
export const DELETE_CUISINE_FAILED = "DELETE_CUISINE_FAILED";

export const UPDATE_FOODSTALL_TIMING_INIT = "UPDATE_FOODSTALL_TIMING_INIT";
export const UPDATE_FOODSTALL_TIMING_SUCCESS = "UPDATE_FOODSTALL_TIMING_SUCCESS";
export const UPDATE_FOODSTALL_TIMING_FAILED = "UPDATE_FOODSTALL_TIMING_FAILED";

export const GET_FOODSTALL_TIMING_INIT = "GET_FOODSTALL_TIMING_INIT";
export const GET_FOODSTALL_TIMING_SUCCESS = "GET_FOODSTALL_TIMING_SUCCESS";
export const GET_FOODSTALL_TIMING_FAILED = "GET_FOODSTALL_TIMING_FAILED";

export const ADD_CUSTOMIZE_TYPE_INIT = "ADD_CUSTOMIZE_TYPE_INIT";
export const ADD_CUSTOMIZE_TYPE_SUCCESS = "ADD_CUSTOMIZE_TYPE_SUCCESS";
export const ADD_CUSTOMIZE_TYPE_FAILED = "ADD_CUSTOMIZE_TYPE_FAILED";
export const FETCH_CUSTOMIZE_TYPE_INIT = "FETCH_CUSTOMIZE_TYPE_INIT";
export const FETCH_CUSTOMIZE_TYPE_SUCCESS = "FETCH_CUSTOMIZE_TYPE_SUCCESS";
export const FETCH_CUSTOMIZE_TYPE_FAILED = "FETCH_CUSTOMIZE_TYPE_FAILED";
export const UPDATE_CUSTOMIZE_TYPE_INIT = "UPDATE_CUSTOMIZE_TYPE_INIT";
export const UPDATE_CUSTOMIZE_TYPE_SUCCESS = "UPDATE_CUSTOMIZE_TYPE_SUCCESS";
export const UPDATE_CUSTOMIZE_TYPE_FAILED = "UPDATE_CUSTOMIZE_TYPE_FAILED";
export const DELETE_CUSTOMIZE_TYPE_SUCCESS = "DELETE_CUSTOMIZE_TYPE_SUCCESS";
export const DELETE_CUSTOMIZE_TYPE_FAILED = "DELETE_CUSTOMIZE_TYPE_FAILED";


export const ADD_CUSTOMIZE_FOOD_ITEM_INIT = "ADD_CUSTOMIZE_FOOD_ITEM_INIT";
export const ADD_CUSTOMIZE_FOOD_ITEM_SUCCESS = "ADD_CUSTOMIZE_FOOD_ITEM_SUCCESS";
export const ADD_CUSTOMIZE_FOOD_ITEM_FAILED = "ADD_CUSTOMIZE_FOOD_ITEM_FAILED";
export const FETCH_CUSTOMIZE_FOOD_ITEM_INIT = "FETCH_CUSTOMIZE_FOOD_ITEM_INIT";
export const FETCH_CUSTOMIZE_FOOD_ITEM_SUCCESS = "FETCH_CUSTOMIZE_FOOD_ITEM_SUCCESS";
export const FETCH_CUSTOMIZE_FOOD_ITEM_FAILED = "FETCH_CUSTOMIZE_FOOD_ITEM_FAILED";
export const UPDATE_CUSTOMIZE_FOOD_ITEM_INIT = "UPDATE_CUSTOMIZE_FOOD_ITEM_INIT";
export const UPDATE_CUSTOMIZE_FOOD_ITEM_SUCCESS = "UPDATE_CUSTOMIZE_FOOD_ITEM_SUCCESS";
export const UPDATE_CUSTOMIZE_FOOD_ITEM_FAILED = "UPDATE_CUSTOMIZE_FOOD_ITEM_FAILED";
export const DELETE_CUSTOMIZE_FOOD_ITEM_SUCCESS = "DELETE_CUSTOMIZE_FOOD_ITEM_SUCCESS";
export const DELETE_CUSTOMIZE_FOOD_ITEM_FAILED = "DELETE_CUSTOMIZE_FOOD_ITEM_FAILED";

export const UPDATE_PERSONAL_ID_PIC = "UPDATE_PERSONAL_ID_PIC";
export const UPDATE_FOODSTALL_IMAGES = "UPDATE_FOODSTALL_IMAGES";
export const UPDATE_MENU_IMAGES = "UPDATE_MENU_IMAGES";


export const GET_FOOD_ITEMS_MENU = "GET_FOOD_ITEMS_MENU";
export const UPDATE_FOOD_ITEMS_MENU = "UPDATE_FOOD_ITEMS_MENU";
export const FILTER_FOOD_ITEMS_MENU = "FILTER_FOOD_ITEMS_MENU";
export const UPDATE_STALL_STATUS = "UPDATE_STALL_STATUS";