/********* add the action types below ************ */

export const ADMIN_CHECK_LOGIN = "ADMIN_CHECK_LOGIN";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const ADMIN_CHECK_FETCH_MERCHANT = "ADMIN_CHECK_FETCH_MERCHANT";
export const ADMIN_FETCH_MERCHANT = "ADMIN_FETCH_MERCHANT";
export const ADMIN_FETCH_MERCHANT_FAIL = "ADMIN_FETCH_MERCHANT_FAIL";
export const ADMIN_CREATE_MERCHANT_INIT = "ADMIN_CREATE_MERCHANT_INIT";
export const ADMIN_CREATE_MERCHANT = "ADMIN_CREATE_MERCHANT";
export const ADMIN_MERCHANT_FAILED_TO_CREATE = "MERCHANT_FAILED_TO_CREATE";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ADMIN_MERCHANT_STATUS_UPDATE_INIT = "ADMIN_MERCHANT_STATUS_UPDATE_INIT";
export const ADMIN_MERCHANT_STATUS_UPDATE_SUCCESS = "ADMIN_MERCHANT_STATUS_UPDATE_SUCCESS";
export const ADMIN_MERCHANT_STATUS_UPDATE_FAILED = "ADMIN_MERCHANT_STATUS_UPDATE_FAILED";


export const ADMIN_FORGET_PWD_OTP_INIT = "ADMIN_FORGET_PWD_OTP_INIT";
export const ADMIN_FORGET_PWD_OTP_SUCCESS = "ADMIN_FORGET_PWD_OTP_SUCCESS";
export const ADMIN_FORGET_PWD_OTP_FAIL = "ADMIN_FORGET_PWD_OTP_FAIL";

export const ADMIN_CREATE_NEW_PWD_INIT = "ADMIN_CREATE_NEW_PWD_INIT";
export const ADMIN_CREATE_NEW_PWD_SUCCESS = "ADMIN_CREATE_NEW_PWD_SUCCESS";
export const ADMIN_CREATE_NEW_PWD_FAILED = "ADMIN_CREATE_NEW_PWD_FAILED";

export const ADMIN_SELECTED_MERCHANT = "ADMIN_SELECTED_MERCHANT";
export const ADMIN_SELECTED_MERCHANT_REQUEST = "ADMIN_SELECTED_MERCHANT_REQUEST";
